################################################################################
## Calibration arguments
################################################################################

################################################################################
## Calibration arguments
################################################################################
calibration-model=None
calibration-correction-type=None
spline-calibration-envelope-dict=None
spline-calibration-nodes=10
spline-calibration-amplitude-uncertainty-dict=None
spline-calibration-phase-uncertainty-dict=None
calibration-prior-boundary=reflective

################################################################################
## Data generation arguments
################################################################################

################################################################################
## Data generation arguments
################################################################################
ignore-gwpy-data-quality-check=True
gps-tuple=None
gps-file=None
timeslide-file=None
timeslide-dict=None
trigger-time=1240215503.017
n-simulation=1
data-dict={'L1': '/home/hemantakumar.phurailatpam/GW190425/L-L1_HOFT_C01_T1700406_v3-1240211456-4096.gwf',  'V1': '/home/hemantakumar.phurailatpam/GW190425/V-V1Online_T1700406_v3-1240214000-2000.gwf'}
data-format=None
allow-tape=True
channel-dict={L1:DCS-CALIB_STRAIN_CLEAN_C01_T1700406_v3, V1:Hrec_hoft_16384Hz_T1700406_v3}
fetch-open-data-kwargs=None
frame-type-dict=None
data-find-url=None
data-find-urltype=osdf
gaussian-noise=False
zero-noise=False

################################################################################
## Detector arguments
################################################################################

################################################################################
## Detector arguments
################################################################################
coherence-test=False
detectors=[L1, V1]
duration=160.0
generation-seed=None
psd-dict={'L1': '/home/hemantakumar.phurailatpam/GW190425/TaylorF2-LS_psds_L1.txt', 'V1': '/home/hemantakumar.phurailatpam/GW190425/TaylorF2-LS_psds_V1.txt'}
psd-fractional-overlap=0.5
post-trigger-duration=1.0
sampling-frequency=2048.0
psd-length=32
psd-maximum-duration=1024
psd-method=median
psd-start-time=None
maximum-frequency=512.
minimum-frequency=20.
tukey-roll-off=0.4
resampling-method=lal

################################################################################
## Injection arguments
################################################################################

################################################################################
## Injection arguments
################################################################################
injection=False
injection-dict=None
injection-file=None
injection-numbers=[None]
injection-waveform-approximant=None
injection-frequency-domain-source-model=None
injection-waveform-arguments=None
injection-waveform-generator-constructor-dict=None

################################################################################
## Job submission arguments
################################################################################

################################################################################
## Job submission arguments
################################################################################
accounting=ligo.dev.o4.cbc.pe.bilby
accounting-user=None
label=TF2Ecck_3PN_T1700406
local=False
local-generation=False
generation-pool=local-pool
local-plot=False
outdir=/home/hemantakumar.phurailatpam/GW190425/outdir_TF2Ecck_3PN_T1700406
overwrite-outdir=False
periodic-restart-time=604800
request-disk=2.0
request-memory=8.0
request-memory-generation=None
request-cpus=16
conda-env=None
scheduler=condor
scheduler-args=None
scheduler-module=[None]
scheduler-env=None
scheduler-analysis-time=14-00:00:00
submit=False
condor-job-priority=0
transfer-files=True
additional-transfer-paths=None
environment-variables={'PYTHONPATH': '/home/hemantakumar.phurailatpam/lalsuite-install/lib/python3.11/site-packages', 'LAL_DATADIR': '/home/hemantakumar.phurailatpam/lalsuite-install/share/lal', 'LALSIMULATION_DATADIR': '/home/hemantakumar.phurailatpam/lalsuite-install/share/lalsimulation', 'LAL_PREFIX': '/home/hemantakumar.phurailatpam/lalsuite-install', 'LALSIMULATION_PREFIX': '/home/hemantakumar.phurailatpam/lalsuite-install'}
getenv=None
disable-hdf5-locking=False
log-directory=None
osg=False
desired-sites=None
analysis-executable=None
analysis-executable-parser=None
scitoken-issuer=None
container=None

################################################################################
## Likelihood arguments
################################################################################

calibration-marginalization=False
################################################################################
## Likelihood arguments
################################################################################
distance-marginalization=False
distance-marginalization-lookup-table=None
phase-marginalization=True
time-marginalization=True
jitter-time=True
reference-frame=sky
time-reference=geocent
likelihood-type=GravitationalWaveTransient
calibration-lookup-table=None
number-of-response-curves=1000
roq-folder=None
roq-linear-matrix=None
roq-quadratic-matrix=None
roq-weights=None
roq-weight-format=hdf5
roq-scale-factor=1.0
fiducial-parameters=None
update-fiducial-parameters=False
epsilon=0.025
extra-likelihood-kwargs=None

################################################################################
## Output arguments
################################################################################

################################################################################
## Output arguments
################################################################################
plot-trace=True
plot-data=False
plot-injection=False
plot-spectrogram=False
plot-calibration=False
plot-corner=False
plot-marginal=False
plot-skymap=False
plot-waveform=False
plot-format=png
create-summary=False
email=None
notification=Never
queue=None
existing-dir=None
webdir=None
summarypages-arguments=None
result-format=hdf5
final-result=True
final-result-nsamples=20000

################################################################################
## Prior arguments
################################################################################

################################################################################
## Prior arguments
################################################################################
default-prior=BBHPriorDict
deltaT=0.2
prior-file=None
prior-dict={mass_1 = Constraint(name='mass_1', minimum=1.0,maximum=3.0), mass_2 = Constraint(name='mass_2', minimum=1.0,maximum=3.0), chirp_mass = bilby.gw.prior.UniformInComponentsChirpMass(name='chirp_mass', minimum=1.3,maximum=1.8), mass_ratio = bilby.gw.prior.UniformInComponentsMassRatio(name='mass_ratio', minimum=0.1, maximum=1.), eccentricity = Uniform(name='e0', minimum=0.0, maximum=0.1), luminosity_distance =  PowerLaw(alpha=2, name='luminosity_distance', minimum=10.0, maximum=1000.0, unit='Mpc'), theta_jn = Sine(name='theta_jn'), psi =  Uniform(name='psi', minimum=0, maximum=6.283185307179586), phase = Uniform(name='phase', minimum=0, maximum=6.283185307179586), ra = Uniform(name='ra', minimum=0, maximum=6.283185307179586, boundary='periodic'), dec = Cosine(name='dec'), }
enforce-signal-duration=True

################################################################################
## Post processing arguments
################################################################################

################################################################################
## Post processing arguments
################################################################################
postprocessing-executable=None
postprocessing-arguments=None
single-postprocessing-executable=None
single-postprocessing-arguments=None

################################################################################
## Sampler arguments
################################################################################

################################################################################
## Sampler arguments
################################################################################
sampler=dynesty
sampling-seed=None
n-parallel=1
sampler-kwargs={'nlive': 1000, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'walks': 100, 'resume': True, 'npool': 16}
reweighting-configuration=None
reweight-nested-samples=True

################################################################################
## Waveform arguments
################################################################################

################################################################################
## Waveform arguments
################################################################################
waveform-generator=bilby.gw.waveform_generator.WaveformGenerator
waveform-generator-constructor-dict=None
reference-frequency=20.0
waveform-approximant=TaylorF2Ecck
catch-waveform-errors=True
pn-spin-order=0
pn-tidal-order=0
pn-phase-order=6
pn-amplitude-order=0
numerical-relativity-file=None
waveform-arguments-dict=None
mode-array=[None]
frequency-domain-source-model=bilby.gw.source.lal_eccentric_binary_black_hole_no_spins
conversion-function=None
generation-function=None

################################################################################
## Global settings
################################################################################

cosmology=Planck15

